### ISSUE TITLE
Governance proposal discussion.  

### ISSUE THREAD

**Issue by WaqarMMirza** [atomone-hub/govgen-proposals#1]
I assume that the team intends to have the governance discussion here, in this repo. Can we set up a [forum](https://forum.cosmos.network/) like other chains to discuss governance proposals? I believe most people don't use GitHub and we will have a low participation on GitHub as compared to the dedicated forum. We need that eventually so why not now?

**Comment by gin** [comment]
Perhaps for effective coordination in the early stages, it is a good idea to avoid fragmenting discussions across multiple places.

Eventually, as more people join the discussions, it makes sense to create purpose-specific places for these discussions. (For example, in the case of Ethereum: the Ethereum Magicians forum, the Ethereum Research forum, the EIP GitHub repository, the ERC GitHub repository, Discords, etc.)

It is good to look toward the future, anticipate, and plan though. 👍

**Comment by giunatale** [comment]
Hi @WaqarMMirza thanks for this question, and sorry for the late reply.
We have been having regular weekly townhalls where you are all invited to attend if interested, plus, we are working on alternative platforms that would still use github as backend for messages so people that use it don't need to switch, but for the others that are not familiar, they would be using github wuthout knowing using a dedicated platform. The only caveat they would still need a gh account to discuss, and this is a security measure to avoid spam.

Please stay tuned and check out this repo/discord/X for announcements!

**Comment by giunatale** [comment]
I will close, as as far as I understand it, this **will** be addressed as we all recognize the need. Thanks again for the feedback, and please join us!

**Comment by WaqarMMirza** [comment]
Thank you @giunatale, good to hear that. I am on board and following up on the town halls. Waiting for the "form" to get published so I can share my ideas about governance and others in a proper way.
